version: "3.9"
services:
  postgresql:
    container_name: temporal-postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:${POSTGRESQL_VERSION}
    networks:
      - temporal-network
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  temporal:
    container_name: temporal
    depends_on:
      - postgresql
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
    image: temporalio/auto-setup:${TEMPORAL_VERSION}
    networks:
      - temporal-network
    ports:
      - 7233:7233
  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:${TEMPORAL_ADMINTOOLS_VERSION}
    networks:
      - temporal-network
    stdin_open: true
    tty: true
  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:${TEMPORAL_UI_VERSION}
    networks:
      - temporal-network
    ports:
      - 8080:8080
  worker:
    container_name: un-believable-temporal-worker
    depends_on:
      - temporal
    build: .
    image: simecipol/un_believable
    pull_policy: always
    command: ["poetry", "run", "un_believable", "worker"]
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    mem_limit: 3g
    mem_reservation: 2g
    volumes:
      - ./logs:/tmp/logs/
    networks:
      - temporal-network
  un_believable:
    container_name: un-believable
    depends_on:
      - worker
    build: .
    image: simecipol/un_believable
    pull_policy: always
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - HF_TOKEN=${HF_TOKEN}
    networks:
      - temporal-network
    profiles: ["manual"]
networks:
  temporal-network:
    driver: bridge
    name: temporal-network
